import React, { useState } from "react";
import Head from "next/head";
import Nav from "../Components/Nav/Nav";
import styles from "../styles/createproject.module.css"

function CreateAProject() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create a New Project - Flipify</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}

export default CreateAProject;
