import React from 'react';
import Head from 'next/head';
import styles from '../styles/deploylogs.module.css';
import DashboardNav from '../Components/DashboardNav/DashboardNav';
import DashContent from '../Components/DashboardNav/DashContent';
// import { PrismLight as SyntaxHighlighter } from 'react-syntax-highlighter';
// import jsx from 'react-syntax-highlighter/dist/esm/languages/prism/jsx';
// import prism from 'react-syntax-highlighter/dist/esm/styles/prism/prism';
import Image from 'next/image';
import { useState } from 'react';
import {
    Accordion,
    AccordionItem,
    AccordionButton,
    AccordionPanel,
    AccordionIcon,
    Box,
} from '@chakra-ui/react';

// SyntaxHighlighter.registerLanguage('jsx', jsx);
const codeSnippet = `
   function copyToClipboard(text) {                         
   const elem = document.createElement('textarea');
   elem.value = text;
   document.body.appendChild(elem);
   elem.select();
   document.execCommand('copy');
   document.body.removeChild(elem);
}
function copyToClipboard(text) {
   const elem = document.createElement('textarea');
   elem.value = text;
   document.body.appendChild(elem);
   elem.select();
   document.execCommand('copy');
  `;

const Deploylogs = () => {
    const [openlog1, setOpenlog1] = useState(false);
    const [openlog2, setOpenlog2] = useState(false);
    const [openlog3, setOpenlog3] = useState(false);
    const [openlog4, setOpenlog4] = useState(false);
    const [openlog5, setOpenlog5] = useState(false);

    const toggleLog1 = () => {
        setOpenlog1(!openlog1);
    };
    const toggleLog2 = () => {
        setOpenlog2(!openlog2);
    };
    const toggleLog3 = () => {
        setOpenlog3(!openlog3);
    };
    const toggleLog4 = () => {
        setOpenlog4(!openlog4);
    };
    const toggleLog5 = () => {
        setOpenlog5(!openlog5);
    };
    return (
        <div className="bgContainer dashContainer__Parent">
            <Head>
                <title>Deploy Logs - Flipify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div>&nbsp;</div>
            <div className="gridContainer">
                <DashboardNav />
                <DashContent>
                    <div className={styles.deploy_logs_header}>
                        <h1>Deploy Logs</h1>
                    </div>
                    <Accordion
                        className={styles.accordion_container}
                        allowMultiple
                        defaultIndex={[0]}
                    >
                        <AccordionItem className={styles.accordionItem}>
                            <h2>
                                <AccordionButton>
                                    <Box
                                        flex="1"
                                        textAlign="left"
                                        className={styles.text_title}
                                    >
                                        Deploy to Heroku{' '}
                                        <span className={styles.failure}>
                                            unsuccessful
                                        </span>
                                    </Box>
                                    {/* <AccordionIcon /> */}
                                    <img src="/dropdownarrow.png" />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel
                                className={styles.accordionPanel}
                                pb={4}
                            >
                                <code className={styles.code_snippet}>
                                    {codeSnippet}
                                </code>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>

                    <Accordion
                        className={styles.accordion_container}
                        allowMultiple
                        defaultIndex={[0]}
                    >
                        <AccordionItem>
                            <h2>
                                <AccordionButton>
                                    <Box
                                        flex="1"
                                        textAlign="left"
                                        className={styles.text_title}
                                    >
                                        Deploy to Gatsby Cloud{' '}
                                        <span className={styles.success}>
                                            successful
                                        </span>
                                    </Box>
                                    <img src="/dropdownarrow.png" />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel
                                className={styles.accordionPanel}
                                pb={4}
                            >
                                <code className={styles.code_snippet}>
                                    {codeSnippet}
                                </code>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                    <Accordion
                        className={styles.accordion_container}
                        allowMultiple
                        defaultIndex={[0]}
                    >
                        <AccordionItem>
                            <h2>
                                <AccordionButton>
                                    <Box
                                        flex="1"
                                        textAlign="left"
                                        className={styles.text_title}
                                    >
                                        Deploy to AWS{' '}
                                        <span className={styles.success}>
                                            successful
                                        </span>
                                    </Box>
                                    <img src="/dropdownarrow.png" />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel
                                className={styles.accordionPanel}
                                pb={4}
                            >
                                <code className={styles.code_snippet}>
                                    {codeSnippet}
                                </code>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                    <Accordion
                        className={styles.accordion_container}
                        allowMultiple
                        defaultIndex={[0]}
                    >
                        <AccordionItem>
                            <h2>
                                <AccordionButton>
                                    <Box
                                        flex="1"
                                        textAlign="left"
                                        className={styles.text_title}
                                    >
                                        Deploy to Render{' '}
                                        <span className={styles.success}>
                                            successful
                                        </span>
                                    </Box>
                                    <img src="/dropdownarrow.png" />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel
                                className={styles.accordionPanel}
                                pb={4}
                            >
                                <code className={styles.code_snippet}>
                                    {codeSnippet}
                                </code>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                    <Accordion
                        className={styles.accordion_container}
                        allowMultiple
                        defaultIndex={[0]}
                    >
                        <AccordionItem>
                            <h2>
                                <AccordionButton>
                                    <Box
                                        flex="1"
                                        textAlign="left"
                                        className={styles.text_title}
                                    >
                                        Deploy to Begin{' '}
                                        <span className={styles.failure}>
                                            unsuccessful
                                        </span>
                                    </Box>
                                    <img src="/dropdownarrow.png" />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel
                                className={styles.accordionPanel}
                                pb={4}
                            >
                                <code className={styles.code_snippet}>
                                    {codeSnippet}
                                </code>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                    {/* <div className={styles.deploy_logs_header}>
            <h1>Deploy Logs</h1>
          </div>


          <div className={styles.deploy_actions_container}>
            <div className={styles.deploy_actions}
            onClick={toggleLog1}
            >
                <h1>Deploy To Heroku <span style={{color:'red'}}>unsuccessful</span></h1>
                <Image src="/dropdownarrow.png" width={15} height={10} alt="dropdown"/>
            </div>
            {openlog1 && <div className={styles.code}>
              <div className={styles.code_inner}>
                <code>
                {codeSnippet}
                </code>
              </div>
            </div>
            }
            <div className={styles.deploy_actions}
            onClick={toggleLog2}
            >
                <h1>Deploy To Gatsby Cloud <span style={{color:'#20B826'}}>successful</span></h1>
                <Image src="/dropdownarrow.png" width={15} height={10} alt="dropdown"/>
            </div>
            {openlog2 && 
            <div className={styles.code}>
              <div className={styles.code_inner}>
                <code>
                {codeSnippet}
                </code>
              </div>
            </div>
            }
            <div className={styles.deploy_actions}
            onClick={toggleLog3}
            >
                <h1>Deploy To AWS <span style={{color:'#20B826'}}
                
                >successful</span></h1>
                <Image src="/dropdownarrow.png" width={15} height={10} alt="dropdown"/>
            </div>
            {openlog3 && 
              <div className={styles.code}>
              <div className={styles.code_inner}>
                <code>
                {codeSnippet}
                </code>
              </div>
            </div>
            }
            
            <div className={styles.deploy_actions}
            onClick={toggleLog4}
            >
                <h1>Deploy To Render <span style={{color:'#20B826'}}
                
                >successful</span></h1>
                <Image src="/dropdownarrow.png" width={15} height={10} alt="dropdown"/>
            </div>
            {
              openlog4 &&
              <div className={styles.code}>
              <div className={styles.code_inner}>
                <code>
                {codeSnippet}
                </code>
              </div>
            </div>
            }
            
            <div className={styles.deploy_actions}
            onClick={toggleLog5}
            >
                <h1>Deploy To Begin <span style={{color:'red'}}>unsuccessful</span></h1>
                <Image src="/dropdownarrow.png" width={20} height={20} alt="dropdown"/>
            </div>
            {
              openlog5 &&
              <div className={styles.code}>
              <div className={styles.code_inner}>
                <code>
                {codeSnippet}
                </code>
              </div>
            </div>
            }
          </div>  */}
                </DashContent>
            </div>
        </div>
    );
};

export default Deploylogs;
