import { useEffect } from 'react';
import Head from 'next/head';
import Arrow from '../public/arrowhome.svg';
import Logo from '../public/logo.png';
import Image from 'next/image';
import Link from 'next/link';
import DashboardVideo from '../Components/Video/DashboardVideo';
import { useSession, signIn, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter();
    const { data: session, status } = useSession();

    useEffect(() => {
        if (session && status === 'authenticated') {
            router.push(`/panel`);
            console.log(session);
        }
    }, [session, status]);

    return (
        <div className="bgContainer">
            <Head>
                <title>Flipify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="home_container">
                <div className="navbar_home">
                    <div className="navbar_home_logo">
                        <Image
                            src={Logo}
                            alt="Nav Logo"
                            width={150}
                            height={40}
                        />
                    </div>
                    <div className="navList">
                        <ul>
                            <li>
                                <Link href="/creators">The Team</Link>
                            </li>
                            <li>How it works</li>
                            <li>
                                <Link href="https://flipify.dev/docs">
                                    Docs
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="body_home">
                    <div className="body_home_inner">
                        <div className="body_home_main">
                            <div className="body_home_main_one">
                                <p>
                                    Switch from one hosting to a backup hosting
                                    just by flipping a switch
                                </p>
                                <button onClick={() => signIn('github')}>
                                    LOGIN WTH GITHUB
                                </button>
                            </div>
                            <div className="arrow_home">
                                <Image
                                    src={Arrow}
                                    alt="arow-down"
                                    width={50}
                                    height={50}
                                />
                            </div>
                            <div className="body_home_main_two">
                                <p className="flipify_works">
                                    HOW FLIPIFY WORKS
                                </p>
                                <p className="immune">
                                    A new way to be immune to server downtime
                                </p>
                                <div className="video_flipify">
                                    <DashboardVideo />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
