import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import DashboardNav from "../Components/DashboardNav/DashboardNav";
import DashboardNavMobile from "../Components/DashboardNav/DashboardNavMobile";
import DashContent from "../Components/DashboardNav/DashContent";
import styles from "../styles/panel.module.css";
import {
  BackendIco,
  FrontendIco,
  DataBaseIco,
  CheckPurp,
  StatsIco,
} from "../Components/SVG/Svgs";
import Card from "react-bootstrap/Card";
import Col from "react-bootstrap/Col";
import Row from "react-bootstrap/Row";
import PanelCards from "../Components/PanelCards/PanelCards";
import panelDetails from "../Components/PanelCards/PanelDetails";

function Cards({ id, serverStatus, image, fe, be, db }) {
  return (
    <PanelCards
      key={id}
      serverStatus={serverStatus}
      image={image}
      fe={fe}
      be={be}
      db={db}
      styles={styles}
    />
  );
}

function Panel() {
  return (
    <div className="bgContainer dashContainer__Parent">
      <Head>
        <title>Panel - Flipify</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>&nbsp;</div>
      <div className="gridContainer">
        <DashboardNav />
        <DashboardNavMobile />
        <DashContent>
          <div className={styles.panel__Parent}>
            <h2>Control Panel</h2>
            <div className={styles.panel_currentHost_ArchiDiv}>
              <Row>
                <Col className={`${styles.panel_CurHostDiv} h-100`}>
                  <h3>Your current hosting service</h3>
                  <Card
                    className={`${styles.panel_CurHostCard} ${styles.panel_ArchiCard} h-100`}
                  >
                    <div className={styles.panel_CurHostCard__Inner}>
                      <div className={styles.panel_CurHostCard__Col1}>
                        <img src="/Heroku_logo.png" alt="host icon" />
                        <div className={styles.panel__CurHostCard_ServerStats}>
                          <p>
                            Server Status: <span>Operational</span>
                          </p>
                        </div>
                        <div
                          className={styles.panel__CurHostCard_MoreServerStats}
                        >
                          <StatsIco /> <p>Info</p>
                        </div>
                      </div>
                      <div className={styles.panel_CurHostCard__Col2}>
                        <CheckPurp /> <p>Running</p>
                      </div>
                    </div>
                  </Card>
                </Col>

                <Col className={`${styles.panel_ArchiDiv} h-100`}>
                  <h3>Website architecture</h3>
                  <Card className={`${styles.panel_ArchiCard} h-100`}>
                    <div className={styles.panel_ArchiCard__Inner}>
                      <div className={styles.panel_ArchiCard__contentParent}>
                        <BackendIco className={styles.backendIco} />{" "}
                        <FrontendIco /> <DataBaseIco />
                      </div>
                      <div className={styles.panel_ArchiCard__contentParent}>
                        <p>Backend:</p> <p>Frontend:</p> <p>Database:</p>
                      </div>
                      <div className={styles.panel_ArchiCard__contentParent}>
                        <p>Ruby</p> <p>React</p>
                        <p>Yes</p>
                      </div>
                    </div>
                  </Card>
                </Col>
              </Row>
            </div>

            <div className={styles.panel_AltParent}>
              <h3>Alternative hosting services</h3>
              <div className={styles.panel_AltCards_Div}>
                <Row>{panelDetails.map(Cards)}</Row>
              </div>
            </div>
          </div>
        </DashContent>
      </div>
    </div>
  );
}

export default Panel;
