import React, { useState, useEffect } from "react";
import Head from "next/head";
import HProviders from "../Components/hostingProviders/hostProviders/hProviders";
import providersDetails from "../Components/hostingProviders/hostProviders/ProvidersDetails";
import HArchi from "../Components/hostingProviders/hArchitecture/hArchi";
import archiDetails from "../Components/hostingProviders/hArchitecture/archiDetails";
import styles from "../styles/selectHost.module.css";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import { HArchiArrow, YesIco, NoIco } from "../Components/SVG/Svgs";
import Nav from "../Components/Nav/Nav";

function hostCard(prop) {
  return <HProviders key={prop.id} image={prop.image} />;
}

function archiCard(prop) {
  return <HArchi key={prop.id} image={prop.image} />;
}

function SelectHost() {
  useEffect(() => {
    document.body.style.overflowY = "auto";
  }, []);

  const [toggleNext, setToggleNext] = useState(false);
  const showNextInput = () => {
    if (toggleNext) {
      return (
        <div className={styles.host__ProjectName}>
          <div className={styles.host__ProjectName__inside}>
            <p>Name this project</p>
            <input
              className={styles.host__Input}
              type="text"
              placeholder="Enter project name"
            />
            <button>Next</button>
            <p onClick={() => setToggleNext(false)}>Skip</p>
          </div>
        </div>
      );
    }
  };
  return (
    <div className="bgContainer">
      <Head>
        <title>Choose Hosting Provider - Flipify</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.containerParent}>
        <Nav />
        <section className={styles.host__section}>
          <h2>Select your current hosting provider</h2>
          <div className={styles.hostParent}>
            <Container>
              <Row>{providersDetails.map(hostCard)}</Row>
            </Container>
          </div>
        </section>

        <section className={styles.host__section}>
          <h2>Select your site architecture</h2>
          <div className={styles.host__archiParent}>
            <div className={styles.host__archiFlex}>
              <div className={styles.host__archiDetails}>
                <Container>
                  <p className={styles.host__stack}>Backend</p>
                  <Row>{archiDetails.map(archiCard)}</Row>
                </Container>
              </div>
              <HArchiArrow className={styles.host_archiArrow} />

              <div className={styles.host__archiDetails}>
                <Container>
                  <p className={styles.host__stack}>Frontend</p>
                  <Row>{archiDetails.map(archiCard)}</Row>
                </Container>
              </div>
              <HArchiArrow
                className={`${styles.host_archiArrow} ${styles.host_archiArrow2_FlexEdit}`}
              />
              <div
                className={`${styles.host__archiDetails} ${styles.host__archiDetails___DB}`}
              >
                <Container>
                  <p className={styles.host__stack}>Database</p>
                  <Row>
                    <div className={styles.hostArchi__dbRow}>
                      <div className={`${styles.hostArchi_Cards_DB}`}>
                        <YesIco className={styles.dbIco} /> <p>Yes</p>
                      </div>
                    </div>
                    <div className={styles.hostArchi__dbRow}>
                      <div className={`${styles.hostArchi_Cards_DB}`}>
                        <NoIco className={styles.dbIco} /> <p>No</p>
                      </div>
                    </div>
                    <div className={styles.hostArchi__dbRow}>
                      <div className={`${styles.hostArchi_Cards_DB}`}>
                        &nbsp;
                      </div>
                    </div>
                  </Row>
                </Container>
              </div>
            </div>
            <button
              onClick={() => setToggleNext(true)}
              className={`${styles.host__NextBtn} nextBtn`}
            >
              Next
            </button>
          </div>
        </section>
        {showNextInput()}
      </div>
    </div>
  );
}

export default SelectHost;
